public class StringSpacePrinter {
  public static void main(String[] args) {
    String[] arr = new String[]{
        "Christ is my reward\n",
        "And all of my devotion\n",
        "Now there's nothing in this world\n",
        "That could ever satisfy\n",
        "\n",
        "Through every trial\n",
        "My soul will sing\n",
        "No turning back\n",
        "I've been set free\n",
        "\n",
        "Christ is enough for me\n",
        "Christ is enough for me\n",
        "Everything I need is in You\n",
        "Everything I need\n",
        "\n",
        "Christ my all in all\n",
        "The joy of my salvation\n",
        "And this hope will never fail\n",
        "Heaven is our home\n",
        "\n",
        "Through every storm\n",
        "My soul will sing\n",
        "Jesus is here\n",
        "To God be the glory\n",
        "\n",
        "Christ is enough for me\n",
        "Christ is enough for me\n",
        "Everything I need is in You\n",
        "Everything I need\n",
        "\n",
        "I have decided to follow Jesus\n",
        "No turning back\n",
        "No turning back\n",
        "\n",
        "I have decided to follow Jesus\n",
        "No turning back\n",
        "No turning back (the cross)\n",
        "\n",
        "The cross before me\n",
        "The world behind me\n",
        "No turning back\n",
        "No turning back\n",
        "\n",
        "The cross before me\n",
        "The world behind me\n",
        "No turning back\n",
        "No turning back\n",
        "\n",
        "Christ is enough for me\n",
        "Christ is enough for me\n",
        "Everything I need is in You\n",
        "Everything I need (Christ is enough)\n",
        "\n",
        "Christ is enough for me\n",
        "Christ is enough for me\n",
        "Everything I need is in You\n",
        "Everything I need\n",
        "\n",
        "I have decided to follow Jesus\n",
        "No turning back\n",
        "No turning back\n",
        "\n",
        "I have decided to follow Jesus\n",
        "No turning back\n",
        "No turning back (I have decided)\n",
        "\n",
        "I have decided to follow Jesus\n",
        "No turning back\n",
        "No turning back\n",
        "\n",
        "I have decided to follow Jesus\n",
        "No turning back\n",
        "No turning back\n"
    };


    for (String line : arr) {
      System.out.print(line);
      if (!line.equals("\n")) {
        System.out.println();
      }
    }
  }
}
